---
title: ''
description: ''
author: CrayBuy
email: craybuy@gmail.com
logo_name: Coupon Store
logo: "/uploads/logo.jpg"
lang: en_IN
social:
  name: ''
  links:
  - https://twitter.com/
  - https://www.facebook.com/
  - https://www.linkedin.com/in/
  - https://github.com/
twitter:
  card: ''
  username: ''
facebook:
  app_id: ''
  publisher: ''
  admins: ''
show_downloads: false
google_site_verification: ''
google_analytics: ''
webmaster_verifications:
  google: ''
  bing: ''
  alexa: ''
  yandex: ''
  baidu: ''
sass:
  style: compressed
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-seo-tag
- jekyll-github-metadata
- jekyll-redirect-from
- jekyll-admin
- jekyll-watch
