---
title: ''
description: ''
author: CrayBuy
email: craybuy@gmail.com
logo_name: CrayBuy
logo: "/assets/logo.jpg"
lang: en
social:
  name: ''
  links:
  - https://twitter.com/
  - https://www.facebook.com/
  - https://www.linkedin.com/in/
  - https://github.com/
twitter:
  card: ''
  username: ''
facebook:
  app_id: ''
  publisher: ''
  admins: ''
show_downloads: false
google_site_verification: ''
google_analytics: <!-- Global site tag (gtag.js) - Google Analytics --> <script async
  src="https://www.googletagmanager.com/gtag/js?id=UA-151734710-1"></script> <script>   window.dataLayer
  = window.dataLayer || [];   function gtag(){dataLayer.push(arguments);}   gtag('js',
  new Date());    gtag('config', 'UA-151734710-1'); </script>
webmaster_verifications:
  google: google-site-verification=U7zQtn34-GtiWoH_lvldd30KVQEUVFIVrfRg48Z8jM0
  bing: ''
  alexa: ''
  yandex: ''
  baidu: ''
sass:
  style: compressed
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-seo-tag
- jekyll-github-metadata
- jekyll-redirect-from
- jekyll-admin
- jekyll-watch
