---
label: default
hide_body: false
fields:
- name: layout
  label: Layout
  type: text
  hidden: true
  default: default
  config:
    required: true
- name: logo
  type: file
  config:
    maxSize: '2'
  label: Logo
  description: Site Logo
  default: "/uploads/logo.jpg"
pages:
- index.html
- simple.md
