---
label: default
hide_body: false
fields:
- name: layout
  label: Layout
  type: text
  hidden: true
  default: default
  config:
    required: true
- name: date
  type: datetime
  label: Date
  description: ''
  config:
    required: true
    date_format: 
    time_format: 
    display_utc: false
  default: now
- name: permalink
  type: text
  config:
    required: false
  label: Permalink
- name: title
  type: text
  config:
    required: true
  label: Title
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
- name: image
  type: file
  config:
    maxSize: 2
  label: OG-Image
  default: "/assets/logo.jpg"
pages:
- privacy-policy-opt-out.md
- about-us.md
- terms-and-conditions-and-grievance-redressal-policy.md
- about-us.md
- privacy-policy-opt-out.md
- terms-and-conditions-and-grievance-redressal-policy.md
- 404.md
